openapi: 3.0.0
info:
  title: Concert Ticket Marketplace API
  version: 1.0.0
  description: API for the decentralized concert ticket marketplace smart contract.

paths:
  /events:
    get:
      summary: Get all events
      responses:
        '200':
          description: A list of events.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
    post:
      summary: Create a new event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '201':
          description: Event created successfully.

  /events/{eventId}:
    get:
      summary: Get a single event
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: The event object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'

  /tickets:
    post:
      summary: Purchase a ticket
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                eventId:
                  type: integer
                seatId:
                  type: integer
      responses:
        '200':
          description: Ticket purchased successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'

  /users/{walletAddress}/tickets:
    get:
      summary: Get tickets for a user
      parameters:
        - name: walletAddress
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of tickets owned by the user.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ticket'

components:
  schemas:
    Event:
      type: object
      properties:
        eventId:
          type: integer
        name:
          type: string
        date:
          type: integer
        ticketPrice:
          type: integer
        totalSupply:
          type: integer
        sold:
          type: integer
        organizer:
          type: string
        isAssignedSeating:
          type: boolean
        totalSeats:
          type: integer

    Ticket:
      type: object
      properties:
        eventId:
          type: integer
        tokenId:
          type: integer
        owner:
          type: string
        isAssentedSeating:
          type: boolean
        seatId:
          type: integer
