openapi: 3.0.0
info:
  title: Concert Ticket Marketplace API
  version: 1.0.0
paths:
  /concerts/{concertId}/seats/{seatId}:
    get:
      summary: Get the owner of a specific seat
      parameters:
        - name: concertId
          in: path
          required: true
          schema:
            type: integer
        - name: seatId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: The address of the seat owner
          content:
            application/json:
              schema:
                type: object
                properties:
                  owner:
                    type: string
    post:
      summary: Purchase a ticket for a specific seat
      parameters:
        - name: concertId
          in: path
          required: true
          schema:
            type: integer
        - name: seatId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Transaction successful
